# Generated by Django 3.2.9 on 2022-06-30 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20220627_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squad',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='squad',
            name='squadMembers',
            field=models.ManyToManyField(blank=True, related_name='squadMembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
