# Generated by Django 3.2.9 on 2022-07-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220704_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(default='profile.png', null=True, upload_to=''),
        ),
    ]
